In [11]:
from scipy.stats import randint as sp_randint
import pandas as pd
import numpy as np
from sklearn import svm
from sklearn.model_selection import train_test_split
from sklearn.tree import DecisionTreeClassifier
from sklearn.preprocessing import MinMaxScaler
from sklearn.svm import SVC
from sklearn.metrics import accuracy_score, confusion_matrix, classification_report
from sklearn.model_selection import StratifiedKFold, GridSearchCV
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import accuracy_score
from sklearn import metrics
from sklearn.metrics import mean_squared_error

In [12]:
import pandas as pd

# Đọc dữ liệu từ tệp CSV
file_path = "./archive/diabetes_prediction_dataset.csv"
data = pd.read_csv(file_path)  # Có dòng tiêu đề

# Lấy 5000 dòng dữ liệu, bao gồm dòng tiêu đề
selected_data = data.head(10000)

# In thông tin 5 dòng đầu tiên của dữ liệu đã lấy
selected_data.head()


gender   age  hypertension  heart_disease smoking_history    bmi   
0  Female  80.0             0              1           never  25.19  \
1  Female  54.0             0              0         No Info  27.32   
2    Male  28.0             0              0           never  27.32   
3  Female  36.0             0              0         current  23.45   
4    Male  76.0             1              1         current  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [13]:
output_file_path = "selected_data.csv"
selected_data.to_csv(output_file_path, index=False)

print("Dữ liệu đã được xuất ra tệp:", output_file_path)

Dữ liệu đã được xuất ra tệp: selected_data.csv


In [14]:
import pandas as pd

# Đường dẫn đến tệp CSV
csv_file_path = "./selected_data.csv"

# Đọc dữ liệu từ tệp CSV
data = pd.read_csv(csv_file_path)

# Hiển thị dữ liệu
data

gender   age  hypertension  heart_disease smoking_history    bmi   
0     Female  80.0             0              1           never  25.19  \
1     Female  54.0             0              0         No Info  27.32   
2       Male  28.0             0              0           never  27.32   
3     Female  36.0             0              0         current  23.45   
4       Male  76.0             1              1         current  20.14   
...      ...   ...           ...            ...             ...    ...   
9995  Female   9.0             0              0           never  25.28   
9996    Male  59.0             0              0            ever  35.00   
9997    Male   2.0             0              0           never  17.43   
9998    Male  61.0             1              0            ever  31.89   
9999    Male  43.0             0              0           never  30.24   

      HbA1c_level  blood_glucose_level  diabetes  
0             6.6                  140         0  
1             6.6                   80         0  
2             5.7                  158         0  
3             5.0                  155         0  
4             4.8                  155         0  
...           ...                  ...       ...  
9995          5.8                  130         0  
9996          6.8                  140         1  
9997          4.5                  126         0  
9998          5.7                  140         0  
9999          6.6                  130         0  

[10000 rows x 9 columns]

In [15]:
data['smoking_history'] = data['smoking_history'].replace({'No Info': 0, 'never': 1, 'former': 2, 'current': 3, 'not current': 4, 'ever':5})
data['gender'] = data['gender'].replace({'Male': 1, 'Female': 0})
data.head(5)

gender   age  hypertension  heart_disease  smoking_history    bmi   
0       0  80.0             0              1                1  25.19  \
1       0  54.0             0              0                0  27.32   
2       1  28.0             0              0                1  27.32   
3       0  36.0             0              0                3  23.45   
4       1  76.0             1              1                3  20.14   

   HbA1c_level  blood_glucose_level  diabetes  
0          6.6                  140         0  
1          6.6                   80         0  
2          5.7                  158         0  
3          5.0                  155         0  
4          4.8                  155         0

In [16]:
from sklearn.preprocessing import MinMaxScaler      


scaler = MinMaxScaler()
data['age'] = scaler.fit_transform(data[['age']])
data['bmi'] = scaler.fit_transform(data[['bmi']])
data['HbA1c_level'] =scaler.fit_transform(data[['HbA1c_level']])
data['blood_glucose_level'] = scaler.fit_transform(data[['blood_glucose_level']])
data.head(5)  # In ra một số dòng đầu của dữ liệu


gender       age  hypertension  heart_disease  smoking_history       bmi   
0       0  1.000000             0              1                1  0.192860  \
1       0  0.674675             0              0                0  0.219921   
2       1  0.349349             0              0                1  0.219921   
3       0  0.449449             0              0                3  0.170753   
4       1  0.949950             1              1                3  0.128700   

   HbA1c_level  blood_glucose_level  diabetes  
0     0.563636             0.272727         0  
1     0.563636             0.000000         0  
2     0.400000             0.354545         0  
3     0.272727             0.340909         0  
4     0.236364             0.340909         0

In [17]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10000 entries, 0 to 9999
Data columns (total 9 columns):
 #   Column               Non-Null Count  Dtype  
---  ------               --------------  -----  
 0   gender               10000 non-null  int64  
 1   age                  10000 non-null  float64
 2   hypertension         10000 non-null  int64  
 3   heart_disease        10000 non-null  int64  
 4   smoking_history      10000 non-null  int64  
 5   bmi                  10000 non-null  float64
 6   HbA1c_level          10000 non-null  float64
 7   blood_glucose_level  10000 non-null  float64
 8   diabetes             10000 non-null  int64  
dtypes: float64(4), int64(5)
memory usage: 703.3 KB


In [18]:
data.isnull().sum()

gender                 0
age                    0
hypertension           0
heart_disease          0
smoking_history        0
bmi                    0
HbA1c_level            0
blood_glucose_level    0
diabetes               0
dtype: int64

In [19]:
X = data.drop(["diabetes"], axis = 1)
y = data["diabetes"]

In [20]:
print(X.shape)
print(y.shape)

(10000, 8)
(10000,)


In [21]:
data["diabetes"].value_counts()

diabetes
0    9141
1     859
Name: count, dtype: int64

In [22]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.3, random_state = 50)
MinMax = MinMaxScaler(feature_range= (0,1))
X_train = MinMax.fit_transform(X_train)
X_test = MinMax.transform(X_test)

In [23]:
data

gender       age  hypertension  heart_disease  smoking_history   
0          0  1.000000             0              1                1  \
1          0  0.674675             0              0                0   
2          1  0.349349             0              0                1   
3          0  0.449449             0              0                3   
4          1  0.949950             1              1                3   
...      ...       ...           ...            ...              ...   
9995       0  0.111612             0              0                1   
9996       1  0.737237             0              0                5   
9997       1  0.024024             0              0                1   
9998       1  0.762262             1              0                5   
9999       1  0.537037             0              0                1   

           bmi  HbA1c_level  blood_glucose_level  diabetes  
0     0.192860     0.563636             0.272727         0  
1     0.219921     0.563636             0.000000         0  
2     0.219921     0.400000             0.354545         0  
3     0.170753     0.272727             0.340909         0  
4     0.128700     0.236364             0.340909         0  
...        ...          ...                  ...       ...  
9995  0.194003     0.418182             0.227273         0  
9996  0.317495     0.600000             0.272727         1  
9997  0.094270     0.181818             0.209091         0  
9998  0.277982     0.400000             0.272727         0  
9999  0.257019     0.563636             0.227273         0  

[10000 rows x 9 columns]

In [24]:
print("X_train: ", X_train,"\n", "y_train: \n", y_train)

X_train:  [[0.         0.7997998  1.         ... 0.29740151 0.23636364 0.02272727]
 [1.         0.34934935 0.         ... 0.29019279 0.09090909 0.20909091]
 [1.         0.62462462 0.         ... 0.53478625 0.23636364 0.27272727]
 ...
 [1.         0.82482482 0.         ... 0.31902766 0.27272727 0.04545455]
 [0.         0.32432432 0.         ... 0.47862531 0.4        0.27272727]
 [0.         0.36186186 0.         ... 0.44476111 0.49090909 0.        ]] 
 y_train: 
 5189    0
7969    0
9039    0
5208    0
506     0
       ..
8262    0
6214    0
8324    0
6253    0
5600    0
Name: diabetes, Length: 7000, dtype: int64


Algorithm ID3 *********************************************

In [25]:
class Node():
    def __init__(self, feature_index=None, threshold=None, left=None, right=None, info_gain=None, value=None):
        ''' Xây dựng ''' 
        
        # cho nút quyết định
        self.feature_index = feature_index
        self.threshold = threshold
        self.left = left
        self.right = right
        self.info_gain = info_gain
        
        # cho nút lá
        self.value = value

In [26]:
class DecisionTreeClassifier_handmade():
    def get_params(self, deep = False):
        return {}
    def __init__(self, min_samples_split=2, max_depth=2):
        ''' constructor '''
        
        # khởi tạo gốc của cây 
        self.root = None
        
        # điều kiện dừng
        self.min_samples_split = min_samples_split
        self.max_depth = max_depth
        
    def build_tree(self, dataset, curr_depth=0):
        ''' hàm đệ quy để xây dựng cây''' 
        
        X, Y = dataset[:,:-1], dataset[:,-1]
        num_samples, num_features = np.shape(X)
        
        # chia nhỏ cho đến khi các điều kiện dừng được đáp ứng
        if num_samples>=self.min_samples_split and curr_depth<=self.max_depth:
            # chia nhỏ cho đến khi các điều kiện dừng được đáp ứng
            best_split = self.get_best_split(dataset, num_samples, num_features)
            # kiểm tra xem thông tin thu được có tích cực không
            if best_split["info_gain"]>0:
                # tái diễn trái
                left_subtree = self.build_tree(best_split["dataset_left"], curr_depth+1)
                # tái diễn phải
                right_subtree = self.build_tree(best_split["dataset_right"], curr_depth+1)
                # trả lại nút quyết định
                return Node(best_split["feature_index"], best_split["threshold"], 
                            left_subtree, right_subtree, best_split["info_gain"])
        
        # tính toán nút lá
        leaf_value = self.calculate_leaf_value(Y)
        # trả lại nút lá
        return Node(value=leaf_value)
    
    def get_best_split(self, dataset, num_samples, num_features):
        ''' chức năng để tìm sự phân chia tốt nhất '''
        
        # từ điển để lưu trữ sự phân chia tốt nhất
        best_split = {}
        max_info_gain = -float("inf")
        
        # lặp lại tất cả các tính năng
        for feature_index in range(num_features):
            feature_values = dataset[:, feature_index]
            possible_thresholds = np.unique(feature_values)
            # lặp lại tất cả các giá trị tính năng có trong dữ liệu
            for threshold in possible_thresholds:
                # nhận được sự phân chia hiện tại
                dataset_left, dataset_right = self.split(dataset, feature_index, threshold)
                # kiểm tra xem các con không rỗng
                if len(dataset_left)>0 and len(dataset_right)>0:
                    y, left_y, right_y = dataset[:, -1], dataset_left[:, -1], dataset_right[:, -1]
                    # tính toán thu được thông tin
                    curr_info_gain = self.information_gain(y, left_y, right_y, "gini")
                    # cập nhật sự phân chia tốt nhất nếu cần
                    if curr_info_gain>max_info_gain:
                        best_split["feature_index"] = feature_index
                        best_split["threshold"] = threshold
                        best_split["dataset_left"] = dataset_left
                        best_split["dataset_right"] = dataset_right
                        best_split["info_gain"] = curr_info_gain
                        max_info_gain = curr_info_gain
                        
        # trả lại phần chia tốt nhất
        return best_split
    
    def split(self, dataset, feature_index, threshold):
        ''' chức năng chia nhỏ dữ liệu '''
        
        dataset_left = np.array([row for row in dataset if row[feature_index]<=threshold])
        dataset_right = np.array([row for row in dataset if row[feature_index]>threshold])
        return dataset_left, dataset_right
    
    def information_gain(self, parent, l_child, r_child, mode="entropy"):
        ''' chức năng tính toán information gain '''
        
        weight_l = len(l_child) / len(parent)
        weight_r = len(r_child) / len(parent)
        if mode=="gini":
            gain = self.gini_index(parent) - (weight_l*self.gini_index(l_child) + weight_r*self.gini_index(r_child))
        else:
            gain = self.entropy(parent) - (weight_l*self.entropy(l_child) + weight_r*self.entropy(r_child))
        return gain
    
    def entropy(self, y):
        ''' hàm tính toán entropy '''
        
        class_labels = np.unique(y)
        entropy = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            entropy += -p_cls * np.log2(p_cls)
        return entropy
    
    def gini_index(self, y):
        ''' hàm tính toán chỉ số gini '''
        
        class_labels = np.unique(y)
        gini = 0
        for cls in class_labels:
            p_cls = len(y[y == cls]) / len(y)
            gini += p_cls**2
        return 1 - gini
        
    def calculate_leaf_value(self, Y):
        ''' hàm tính toán nút lá '''
        
        Y = list(Y)
        return max(Y, key=Y.count)
    
    def print_tree(self, tree=None, indent=" "):
        ''' chức năng in cây '''
        
        if not tree:
            tree = self.root

        if tree.value is not None:
            print(tree.value)

        else:
            print("X_"+str(tree.feature_index), "<=", tree.threshold, "?", tree.info_gain)
            print("%sleft:" % (indent), end="")
            self.print_tree(tree.left, indent + indent)
            print("%sright:" % (indent), end="")
            self.print_tree(tree.right, indent + indent)
    
    def fit(self, X, Y):
        ''' chức năng đào tạo cây '''
        
        dataset = np.concatenate((X, Y), axis=1)
        self.root = self.build_tree(dataset)
    
    def predict(self, X):
        ''' chức năng dự đoán tập dữ liệu mới '''
        
        preditions = [self.make_prediction(x, self.root) for x in X]
        return preditions
    
    def make_prediction(self, x, tree):
        ''' chức năng dự đoán một điểm dữ liệu duy nhất '''
        
        if tree.value!=None: return tree.value
        feature_val = x[tree.feature_index]
        if feature_val<=tree.threshold:
            return self.make_prediction(x, tree.left)
        else:
            return self.make_prediction(x, tree.right)

In [33]:
classifier = DecisionTreeClassifier_handmade(min_samples_split=2, max_depth=3)
y_train1 = y_train.to_numpy().reshape(-1,1)
classifier.fit(X_train,y_train1)
classifier.print_tree()

X_6 <= 0.5636363636363636 ? 0.0714534800706518
 left:X_7 <= 0.5454545454545455 ? 0.03419976321938235
  left:X_1 <= 0.6996996996996998 ? 0.001434420786346008
    left:X_5 <= 0.9312657166806371 ? 0.0004083968825006265
        left:0.0
        right:1.0
    right:X_6 <= 0.2727272727272728 ? 0.006795522833659862
        left:0.0
        right:0.0
  right:1.0
 right:1.0


In [37]:
# classifier = DecisionTreeClassifier_handmade(min_samples_split=2, max_depth=3)
y_pred = classifier.predict(X_test)
y_pred_train = classifier.predict(X_train)
print('Accuracy Score DecisionTree Train dataset:', metrics.accuracy_score(y_train, y_pred_train))
print('Accuracy Score DecisionTree Test dataset:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

Accuracy Score DecisionTree Train dataset: 0.973
Accuracy Score DecisionTree Test dataset: 0.9706666666666667
Confusion Matrix:
 [[2741    1]
 [  87  171]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      2742
           1       0.99      0.66      0.80       258

    accuracy                           0.97      3000
   macro avg       0.98      0.83      0.89      3000
weighted avg       0.97      0.97      0.97      3000



In [38]:
from sklearn import tree


print("DecisionTree")
clf = DecisionTreeClassifier(max_depth = 3, min_samples_split = 2)
clf = clf.fit(X_train, y_train)
y_pred = clf.predict(X_test)
y_pred_train = clf.predict(X_train)
print('Accuracy Score DecisionTree Train dataset:', metrics.accuracy_score(y_train, y_pred_train))
print('Accuracy Score DecisionTree Test dataset:', accuracy_score(y_test, y_pred))
print('Confusion Matrix:\n', confusion_matrix(y_test, y_pred))
print('Classification Report:\n', classification_report(y_test, y_pred))

DecisionTree
Accuracy Score DecisionTree Train dataset: 0.9728571428571429
Accuracy Score DecisionTree Test dataset: 0.971
Confusion Matrix:
 [[2742    0]
 [  87  171]]
Classification Report:
               precision    recall  f1-score   support

           0       0.97      1.00      0.98      2742
           1       1.00      0.66      0.80       258

    accuracy                           0.97      3000
   macro avg       0.98      0.83      0.89      3000
weighted avg       0.97      0.97      0.97      3000

